version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "pswrd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
      - ./postgresql_data:/docker-entrypoint-initdb.d
    ports:
      - "5450:5432"