version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "pswrd"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
      - ./postgresql_data:/docker-entrypoint-initdb.d
    expose:
      - "5432"
      - "5450"
    ports:
      - "5450:5432"
    networks:
      default:
        ipv4_address: 172.16.1.4
  fastapiservice:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      default:
        ipv4_address: 172.16.1.6

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24